---

name: Lint code in repository
"on":
  push:
    branches:
      - "main"
  pull_request:
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install yamllint
      - name: Linting - YAML
        run: find . -name '*.yml' | xargs yamllint -s
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black
      - name: Linting - black
        run: black -v --check .
  pylama:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylama
      - name: Linting - pylama
        run: pylama -i E501 .
